// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ICSStudio.ControllerOverviewPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidControllerOverviewPackageString = "57cf9bea-3da0-4c24-b7a0-94a747e6abfa";
        public const string guidControllerOverviewPackageCmdSetString = "6d1dd154-2601-43ca-9396-1c661819ec6e";
        public const string guidImagesString = "ac32b0b3-4690-4cb9-a15a-ad6ed01b8dee";
        public static Guid guidControllerOverviewPackage = new Guid(guidControllerOverviewPackageString);
        public static Guid guidControllerOverviewPackageCmdSet = new Guid(guidControllerOverviewPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CommandGroupId = 0x0100;
        public const int ControllerOverviewCommandId = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
