// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ICSStudio.CommunicationsPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string communicationsCommandPackageString = "6a6fff06-1b39-487b-ae74-9df35ea55aa9";
        public const string communicationsCommandPackageCmdSetString = "cc8cd681-f729-48ed-9619-3653c1cb6e1b";
        public const string guidImagesString = "b1cfe742-c90a-4d47-a70d-2e63245e8a9d";
        public static Guid communicationsCommandPackage = new Guid(communicationsCommandPackageString);
        public static Guid communicationsCommandPackageCmdSet = new Guid(communicationsCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int communicationsMenu = 0x0100;
        public const int communicationsGroup0 = 0x1100;
        public const int communicationsGroup1 = 0x1200;
        public const int communicationsGroup2 = 0x1300;
        public const int communicationsGroup3 = 0x1400;
        public const int communicationsGroup4 = 0x1500;
        public const int OperationMenu = 0x3000;
        public const int whoActiveCommand = 0x1101;
        public const int selectRecentPathCommand = 0x1102;
        public const int selectSoftwareCommand = 0x1103;
        public const int goOnlineCommand = 0x1201;
        public const int uploadCommand = 0x1202;
        public const int downloadCommand = 0x1203;
        public const int programModeCommand = 0x1301;
        public const int runModeCommand = 0x1302;
        public const int testModeCommand = 0x1303;
        public const int lockControllerCommand = 0x1401;
        public const int saveToControllerCommand = 0x1402;
        public const int clearFaultsCommand = 0x1501;
        public const int gotoFaultsCommand = 0x1502;
        public const int controllerPropertiesCommand = 0x1503;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
