// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ICSStudio.ToolsPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string toolsCommandPackageString = "90ddcd4b-b87f-4345-bce6-4b4a4d376a4b";
        public const string toolsCommandPackageCmdSetString = "e22dac82-d881-433e-923e-bd8e0f4724d0";
        public const string guidImagesString = "8e464b79-9855-400c-b5ee-81945a7b9727";
        public static Guid toolsCommandPackage = new Guid(toolsCommandPackageString);
        public static Guid toolsCommandPackageCmdSet = new Guid(toolsCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int toolsMenu = 0x0100;
        public const int toolsGroup0 = 0x1100;
        public const int toolsGroup1 = 0x1200;
        public const int toolsGroup2 = 0x1300;
        public const int toolsGroup3 = 0x1400;
        public const int toolsGroup4 = 0x1500;
        public const int toolsGroup5 = 0x1600;
        public const int toolsGroup6 = 0x1700;
        public const int securityGroup0 = 0x1800;
        public const int securityGroup1 = 0x1900;
        public const int importGroup = 0x1A00;
        public const int exportGroup = 0x1B00;
        public const int optionsCommand = 0x1101;
        public const int securityCommand = 0x1102;
        public const int languagesCommand = 0x1103;
        public const int logOnCommand = 0x1104;
        public const int logOffCommand = 0x1105;
        public const int refreshPrivilegesCommand = 0x1106;
        public const int configureSourceProtectionCommand = 0x1107;
        public const int lockAllUnlockedContentCommand = 0x1108;
        public const int lockComponentCommand = 0x1109;
        public const int unlockComponentCommand = 0x110A;
        public const int importCommand = 0x1201;
        public const int exportCommand = 0x1202;
        public const int importTagsCommand = 0x1203;
        public const int importComponentCommand = 0x1204;
        public const int exportTagsCommand = 0x1205;
        public const int exportComponentCommand = 0x1206;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int updateCommand = 0x110B;
        public const int gatewayCommand = 0x110C;
        public const int compareCommand = 0x110D;
    }
}
