// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ICSStudio.OrganizerPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string organizerPackageString = "f92062fc-89aa-4e53-9e85-ca55b8d4a201";
        public const string organizerPackageCmdSetString = "964dd943-7515-4353-9959-03e5792d62f3";
        public const string guidImagesString = "317cee9b-121d-4921-9051-22cc17805a96";
        public static Guid organizerPackage = new Guid(organizerPackageString);
        public static Guid organizerPackageCmdSet = new Guid(organizerPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int studioViewMenuGroup = 0x0100;
        public const int controllerOrganizerCommand = 0x0101;
        public const int logicalOrganizerCommand = 0x0105;
        public const int newFileCommand = 0x010C;
        public const int historyFileCommand = 0x1E00;
        public const int openFileCommand = 0x010D;
        public const int saveFileCommand = 0x010E;
        public const int saveAsFileCommand = 0x010F;
        public const int buildSaveFileCommand = 0x0110;
        public const int propertiesMenuGroup = 0x0200;
        public const int propertiesCommand = 0x0201;
        public const int controllerPropertiesCommand = 0x0202;
        public const int clipboardMenuGroup = 0x0300;
        public const int controllerContextMenu = 0x1000;
        public const int group0 = 0x1100;
        public const int group1 = 0x1200;
        public const int group2 = 0x1300;
        public const int group3 = 0x1400;
        public const int group4 = 0x1500;
        public const int group5 = 0x1600;
        public const int group6 = 0x1700;
        public const int group7 = 0x1800;
        public const int group8 = 0x1900;
        public const int group9 = 0x1A00;
        public const int newAxisGroup = 0x1B00;
        public const int taskAddGroup = 0x1C00;
        public const int programAddGroup0 = 0x1D00;
        public const int programAddGroup1 = 0x1D10;
        public const int programAddGroup2 = 0x1D20;
        public const int verifyControllerCommand = 0x1101;
        public const int newTagCommand = 0x1102;
        public const int newProgramCommand = 0x1103;
        public const int newTaskCommand = 0x1104;
        public const int newLocalTagCommand = 0x1105;
        public const int newParameterCommand = 0x1106;
        public const int newMotionGroupCommand = 0x1107;
        public const int newAxisMenu = 0x1108;
        public const int newCoordinateSystemCommand = 0x1109;
        public const int newAddOnInstructionCommand = 0x110A;
        public const int newDataTypeCommand = 0x110B;
        public const int newStringTypeCommand = 0x110C;
        public const int newTrendCommand = 0x110D;
        public const int newModuleCommand = 0x110E;
        public const int importProgramCommand = 0x110F;
        public const int importAddOnInstructionCommand = 0x1110;
        public const int importDataTypeCommand = 0x1111;
        public const int importStringTypeCommand = 0x1112;
        public const int importTrendCommand = 0x1113;
        public const int taskAddMenu = 0x1114;
        public const int programAddMenu = 0x1115;
        public const int openCommand = 0x1116;
        public const int openTrendLogCommand = 0x1117;
        public const int discoverModulesCommand = 0x1118;
        public const int gotoModuleCommand = 0x1119;
        public const int importModuleCommand = 0x111A;
        public const int openDefinitionCommand = 0x111B;
        public const int monitorGroupTagCommand = 0x1201;
        public const int monitorAxisTagCommand = 0x1202;
        public const int faultHelpCommand = 0x1301;
        public const int clearMotionGroupFaultsCommand = 0x1302;
        public const int clearAxisFaultsCommand = 0x1303;
        public const int cutCommand = 0x1401;
        public const int copyCommand = 0x1402;
        public const int pasteCommand = 0x1403;
        public const int pasteSpecialMenu = 0x1404;
        public const int pasteWithConfigurationCommand = 0x1405;
        public const int deleteCommand = 0x1406;
        public const int motionDirectCommandsCommand = 0x1501;
        public const int manualTuneCommand = 0x1502;
        public const int motionGeneratorCommand = 0x1503;
        public const int monitorTagsCommand = 0x1504;
        public const int editTagsCommand = 0x1505;
        public const int verifyCommand = 0x1506;
        public const int exportTagsCommand = 0x1507;
        public const int crossReferenceCommand = 0x1508;
        public const int browseLogicCommand = 0x1601;
        public const int findInLogicalOrganizerCommand = 0x1602;
        public const int onlineEditsCommand = 0x1701;
        public const int generateReportCommand = 0x1801;
        public const int printMenu = 0x1802;
        public const int exportProgramCommand = 0x1901;
        public const int exportRoutineCommand = 0x1902;
        public const int exportModuleCommand = 0x1903;
        public const int exportAddOnInstructionCommand = 0x1904;
        public const int exportDataTypeCommand = 0x1905;
        public const int exportStringTypeCommand = 0x1906;
        public const int exportTrendCommand = 0x1907;
        public const int includeInTrackingGroupCommand = 0x1A01;
        public const int AXIS_CIP_DRIVECommand = 0x1B01;
        public const int AXIS_VIRTUALCommand = 0x1B02;
        public const int taskNewProgramCommand = 0x1C01;
        public const int newEquipmentPhaseCommand = 0x1C02;
        public const int newEquipmentSequenceCommand = 0x1C03;
        public const int taskImportProgramCommand = 0x1C04;
        public const int importEquipmentPhaseCommand = 0x1C05;
        public const int importEquipmentSequenceCommand = 0x1C06;
        public const int newRoutineCommand = 0x1D01;
        public const int programNewLocalTagCommand = 0x1D02;
        public const int programNewParameterCommand = 0x1D03;
        public const int importRoutineCommand = 0x1D04;
        public const int newPhaseStateCommand = 0x1D05;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;

        public const int newInToolbarCommand = 0x2001;
        public const int openInToolbarCommand = 0x2002;
        public const int saveInToolbarCommand = 0x2003;
        public const int printInToolbarCommand = 0x2004;
        public const int cutInToolbarCommand = 0x2005;
        public const int copyInToolbarCommand = 0x2006;
        public const int pasteInToolbarCommand = 0x2007;

        public const int printRoutine = 0x0111;
        public const int printRoutineProperties = 0x0112;
        public const int printTags = 0x0113;
        public const int printSequencingAndStepTags = 0x0114;
        public const int printModuleProperties = 0x0115;
        public const int printAdd_OnInstructionSignatures = 0x0116;
        public const int printAdd_OnInstruction = 0x0117;
        public const int printDataType = 0x0118;
        public const int printCrossReference = 0x0119;
        public const int printControllerOrganizer = 0x011A;
        public const int printControllerProperties = 0x011B;
        public const int printTaskProperties = 0x011C;
        public const int printProgramProperties = 0x011D;
        public const int printEquipmentSequence = 0x011E;
        public const int printEntireProject = 0x011F;
        public const int PrintSubMenu = 0x5000;
        public const int PrintGroup = 0x2100;
        public const int printRoutine2 = 0x0C11;
        public const int printRoutineProperties2 = 0x0C12;
        public const int printTags2 = 0x0C13;
        public const int printSequencingAndStepTags2 = 0x0C14;
        public const int printModuleProperties2 = 0x0C15;
        public const int printAdd_OnInstructionSignatures2 = 0x0C16;
        public const int printAdd_OnInstruction2 = 0x0C17;
        public const int printDataType2 = 0x0C18;
        public const int printCrossReference2 = 0x0C19;
        public const int printControllerOrganizer2 = 0x0C1A;
        public const int printControllerProperties2 = 0x0C1B;
        public const int printTaskProperties2 = 0x0C1C;
        public const int printProgramProperties2 = 0x0C1D;
        public const int printEquipmentSequence2 = 0x0C1E;
        public const int printEntireProject2 = 0x0C1F;
        public const int PrintContextMenu = 0x6000;
        public const int PrintGroup2 = 0x2200;
    }
}
